Simplify running build scripts locally
- Add build-all script
- Allow relative paths
- Fix url -> filepath sed invocation

Signed-off-by: Emily Casey <ecasey@pivotal.io>

diff --git a/scripts/build-bosh-deps-tar b/scripts/build-bosh-deps-tar
--- a/scripts/build-bosh-deps-tar
+++ b/scripts/build-bosh-deps-tar
@@ -13,6 +13,11 @@ if [[ -z $manifest ]]; then
   echo "USAGE: build-bosh-deps-tar -m <path-to-bosh-manifest>"
   exit 2
 fi
+if [[ ! -f $manifest ]]; then
+  echo "ERROR: manifest $manifest does not exist"
+  exit 2
+fi
+manifest="$(cd "$(dirname "$manifest")"; pwd)/$(basename "$manifest")"
 
 if [[ -z "$BOSH_ENVIRONMENT" ]]; then
   echo "ERROR: a bosh director is required to compile releases, please set your BOSH_* env variables"
@@ -92,8 +97,9 @@ compile_releases () {
 
 finalize_manifest () {
   releases="$(rq -y <"$manifest" | jq -c '.releases[]')"
+  cp "$manifest" "$releases_dir"/director.yml
   for release in $releases; do
-    sed "s~url:.*$(name "$release").*~url: file:///var/vcap/cache/$(filename "$release")~g" "$manifest" > "$releases_dir"/director.yml
+    sed -i "" "s~url:$(url "$release")~url: file:///var/vcap/cache/$(filename "$release")~g" "$releases_dir"/director.yml
   done
 }
 
diff --git a/scripts/build-cf-deps-iso b/scripts/build-cf-deps-iso
--- a/scripts/build-cf-deps-iso
+++ b/scripts/build-cf-deps-iso
@@ -14,6 +14,12 @@ if [[ -z "$cf_deps" || -z "$bosh_deps" ]]; then
   echo "USAGE: ./build-cf-iso -c <cf-deps-tar> -b <bosh-deps-tar>"
   exit 1
 fi
+if [[ ! -f $cf_deps || ! -f $bosh_deps ]]; then
+  echo "ERROR: Either $manifest of $cloud_config do not exist"
+  exit 2
+fi
+cf_deps="$(cd "$(dirname "$cf_deps")"; pwd)/$(basename "$cf_deps")"
+bosh_deps="$(cd "$(dirname "$bosh_deps")"; pwd)/$(basename "$bosh_deps")"
 
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 output_dir="$script_dir/../output"
diff --git a/scripts/build-cf-deps-tar b/scripts/build-cf-deps-tar
--- a/scripts/build-cf-deps-tar
+++ b/scripts/build-cf-deps-tar
@@ -14,6 +14,12 @@ if [[ -z $manifest || -z $cloud_config ]]; then
   echo "USAGE: build-cf-deps-tar -m <path-to-cf-manifest> -c <path-to-cloud-config>"
   exit 2
 fi
+if [[ ! -f $manifest || ! -f $cloud_config ]]; then
+  echo "ERROR: Either $manifest of $cloud_config do not exist"
+  exit 2
+fi
+manifest="$(cd "$(dirname "$manifest")"; pwd)/$(basename "$manifest")"
+cloud_config="$(cd "$(dirname "$cloud_config")"; pwd)/$(basename "$cloud_config")"
 
 if [[ -z "$BOSH_ENVIRONMENT" ]]; then
   echo "ERROR: a bosh director is required to compile releases, please set your BOSH_* env variables"
@@ -83,8 +89,9 @@ compile_releases () {
 
 finalize_manifest () {
   releases="$(rq -y <"$manifest" | jq -c '.releases[]')"
+  cp "$manifest" "$releases_dir"/deployment.yml
   for release in $releases; do
-    sed "s~url:.*$(name "$release").*~url: file:///var/vcap/cache/$(filename "$release")~g" "$manifest" > "$releases_dir"/deployment.yml
+    sed -i "" "s~url: $(url "$release")~url: file:///var/vcap/cache/$(filename "$release")~g" "$releases_dir"/deployment.yml
   done
 }
 
diff --git a/scripts/generate-bosh-manifest b/scripts/generate-bosh-manifest
--- a/scripts/generate-bosh-manifest
+++ b/scripts/generate-bosh-manifest
@@ -13,6 +13,11 @@ if [[ -z $bosh_deployment ]]; then
   echo "USAGE: generate-bosh-manifest -b <path-to-bosh-deployment>"
   exit 1
 fi
+if [[ ! -f $bosh_deployment ]]; then
+  echo "ERROR: bosh_deployment $bosh_deployment does not exist"
+  exit 2
+fi
+bosh_deployment="$(cd "$(dirname "$bosh_deployment")"; pwd)/$(basename "$bosh_deployment")"
 
 scripts_dir="$(cd "$(dirname "$0")" && pwd)"
 output_dir="$scripts_dir"/../output
diff --git a/scripts/generate-cf-manifest b/scripts/generate-cf-manifest
--- a/scripts/generate-cf-manifest
+++ b/scripts/generate-cf-manifest
@@ -13,6 +13,11 @@ if [[ -z $cf_deployment ]]; then
   echo "USAGE: generate-cf-manifest -c <path-to-cf-deployment>"
   exit 1
 fi
+if [[ ! -f $cf_deployment ]]; then
+  echo "ERROR: cf_deployment $cf_deployment does not exist"
+  exit 2
+fi
+cf_deployment="$(cd "$(dirname "$cf_deployment")"; pwd)/$(basename "$cf_deployment")"
 
 scripts_dir="$(cd "$(dirname "$0")" && pwd)"
 output_dir="$scripts_dir"/../output
